version: '3.3'

services:
  postgresql:
    image: postgres:13
    environment:
      - POSTGRES_DB=worker
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - ./post_data:/var/lib/postgresql/data
    restart: always
    networks:
      - default
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"